superprojectman/projectman/urls.py
from django.conf.urls import url

from projectman import views

app_name = 'projectman'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login.as_view(), name='login'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^logout/$', views.logout, name='logout')
]

superprojectman/superprojectman/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('projectman.urls'))
]

superprojectman/projectman/models/profiles.py
from django.db import models
from .user import User


class ProjectmanagerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cellphone = models.CharField(max_length=10, default="")

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


class DeveloperProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    github = models.CharField(max_length=60, default="")

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


class ClientProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cellphone = models.CharField(max_length=10, default="")

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)

superprojectman/projectman/models/project.py
from django.db import models
from .user import User
from .profiles import ProjectmanagerProfile,ClientProfile,DeveloperProfile


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=500, default="", blank=True)
    project_manager = models.OneToOneField(ProjectmanagerProfile, blank=True, null=True, on_delete=models.CASCADE)
    client = models.ManyToManyField(ClientProfile)
    methodology = models.CharField(max_length=50)
    budget = models.BigIntegerField()
    resources = models.TextField()
    time_start_real = models.DateTimeField(blank=True, null=True)
    time_end_real = models.DateTimeField(blank=True, null=True)
    time_start_estimated = models.DateTimeField(blank=True, null=True)
    time_end_estimated = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title


class Task(models.Model):
    PRIORITY = (
        (1, 'High'),
        (2, 'Medium'),
        (3, 'Low')
    )
    STATE = (
        (1, 'Done'),
        (2, 'In-progess'),
        (3, 'To-do')
    )
    name = models.CharField(max_length=100)
    project = models.ForeignKey(Project, blank=True, null=True, on_delete=models.CASCADE)
    description = models.TextField()
    requeriments = models.TextField()
    costs = models.BigIntegerField()
    estimated_target_date = models.DateTimeField(blank=True, null=True)
    responsable = models.ForeignKey(DeveloperProfile, blank=True, null=True, on_delete=models.CASCADE)
    priority = models.IntegerField(choices=PRIORITY)
    state = models.IntegerField(choices=STATE)

    def __str__(self):
        return self.project.title + " - " + self.name


class Comment(models.Model):
    task = models.ForeignKey(Task, related_name="comment")
    owner = models.ForeignKey(User, related_name="owner")
    comment = models.TextField(max_length=300)
    keyword = models.CharField(max_length=20)
    date_created = models.DateField(auto_now_add=True)

superprojectman/projectman/models/user.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    secret_question = models.CharField(max_length=300,default="what is you user?")
    secret_answer = models.CharField(max_length=300, default="")

superprojectman/projectman/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.views import View

def index(request):
    if request.user.is_authenticated.value:
        return redirect('projectman:dashboard')
    else:
        return render(request, 'projectman/index.html')


class login(View):

    def get(self, request):
        if request.user.is_authenticated and request.user.is_active:
            return redirect('projectman:dashboard')
        else:
            return  render(request, 'projectman/login.html')

    def post(self, request):
        if request.POST.get('username') is None:
            messages.error(request, "Error en usuario y/o contraseña")
        else:
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = auth.authenticate(username=username, password=password)
            if user is not None and user.is_active:
                auth.login(request, user)
                return redirect('projectman:dashboard')
            else:
                return redirect('projectman:login')


@login_required
def dashboard(request):
    return render(request, "projectman/dashboard.html")


@login_required
def logout(request):
    auth.logout(request)
    return redirect('projectman:index')

superprojectman/templates/base/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <title>{% block titulo_ventana %} Titulo de ventana {% endblock %}| Django 1.11</title>

    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'dist/icono.ico' %}" />

    <!-- Bootstrap 3.3.2 -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css " />

    <!-- DATA TABLES -->
    <link href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}" rel="stylesheet" type="text/css" />

    <!-- FontAwesome 4.3.0 -->
    <link href="{% static 'plugins/font-awesome/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- Theme style -->
    <link href="{% static 'dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- bootstrap-select-1.12.4 -->
    <link href="{% static 'plugins/bootstrap-select-1.12.4/css/bootstrap-select.min.css' %}" rel="stylesheet" type="text/css" />

    {#    estilos personalizados#}
    <link href="{% static 'dist/css/mystyles.css' %}" rel="stylesheet" type="text/css" />

    <!-- Estilos extra / OPCIONAL -->
    {% block extrastyle %} 
    {% endblock %}

</head>
<body class="{% if request.user.is_authenticated.value %} skin-blue fixed {% else %} skin-blue fixed sidebar-collapse sidebar-open {% endif %}">
<div class="wrapper">
    {% block header %}
        {# barra principal / nav #}
        {% include 'base/header.html' %}
    {% endblock %}

    {% block sidebar %}
        {# Columna del lado izquierdo. contiene el logo y la barra lateral #}
        {% include 'base/sidebar.html' %}
    {% endblock %}

    {# contenido de la pagina #}
    <!-- Right side column. Contains the navbar and content of the page -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                {% block titulo %}{% endblock %}
                <small>{% block subtitulo %} {% endblock %}</small>
            </h1>
{#            <ol class="breadcrumb">#}
{#                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>#}
{#                <li class="active">Dashboard</li>#}
{#            </ol>#}
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                {% block content %} {% endblock %}
            </div>
        </section>
    </div><!-- ./content-wrapper -->

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 1.0
        </div>
        <strong>Copyright &copy; 2018 <a href="http://oscloud.co" target="_blank">Oscloud Tecnología</a>.</strong> Todos los derechos reservados.
    </footer>

</div><!-- ./wrapper -->

<!-- jQuery 2.1.3 -->
<script src="{% static 'plugins/jQuery/jQuery-2.1.3.min.js' %}"></script>

<!-- jQuery UI 1.11.2 -->
<script src="{% static 'plugins/jQueryUI/jquery-ui.min.js' %}" type="text/javascript"></script>

<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>

<!-- Bootstrap 3.3.2 JS -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>

<!-- DATA TABES SCRIPT -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}" type="text/javascript"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}" type="text/javascript"></script>

<!-- Slimscroll -->
<script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>

<!-- FastClick -->
<script src="{% static 'plugins/fastclick/fastclick.min.js' %}"></script>

<!-- bootstrap-select-1.12.4 -->
<script src="{% static 'plugins/bootstrap-select-1.12.4/js/bootstrap-select.min.js' %}" type="text/javascript"></script>
<script src="{% static 'plugins/bootstrap-select-1.12.4/js/i18n/defaults-es_ES.min.js' %}" type="text/javascript"></script>

<!-- AdminLTE App -->
<script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>

{#Scripts personalizados#}
<script src="{% static 'dist/js/myscripts.js' %}" type="text/javascript"></script>

<!-- JS extra / OPCIONAL -->
{% block extrascript %} {% endblock %}

</body>
</html>

superprojectman/templates/base/header.html
{% load staticfiles %}
<header class="main-header">
    <!-- Logo -->
    <a class="logo" href=""><b>Gestion</b> de la Calidad</a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
        {% if request.user.is_authenticated.value %}
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="user-footer">
                       <a href="{% url 'projectman:logout' %}" role="button">Logout</a>
                    </li>
                </ul>
            </div>
        {% else %}
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="user-footer">
                       <a href="{% url 'projectman:login' %}" role="button">Login</a>
                    </li>
                </ul>
            </div>
        {% endif %}
    </nav>
</header>

superprojectman/templates/base/sidebar.html
{% load staticfiles %}
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                    <img src="" class="img-circle" alt="" />
                    <img src="" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                    <p></p>
                    <p></p>
                <a role="button"><i class="fa fa-circle text-success"></i> En linea</a>
            </div>
        </div>
        <ul class="sidebar-menu">
            <li class="header">MENU DE NAVEGACIÓN</li>
            <li><!-- Inicio -->
                <a href="">
                    <i class="fa fa-home"></i><span>Inicio</span>
                </a>
            </li>
{#            <li class="header">OPCIONES GENERALES</li>#}
            <li class="treeview"><!-- Proyectos -->
                <a href="#">
                    <i class="fa fa-briefcase"></i> <span>Proyectos</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
{#                    <li class="active"><a href="#"><i class="fa fa-circle-o"></i> Nuevo</a></li>#}
                    <li><a href=""><i class="fa fa-circle-o"></i> Nuevo</a></li>
                    <li><a href=""><i class="fa fa-circle-o"></i> Lista</a></li>
                </ul>
            </li>
                        
            <li class="header">HERRAMIENTAS</li>
            <li class="treeview"><!-- Lluvia de ideas -->
                <a href="#">
                    <i class="fa fa-umbrella"></i>
                    <span>Lluvia de ideas</span><i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href=""><i class="fa fa-circle-o"></i> Nueva idea</a></li>
                    <li><a href=""><i class="fa fa-circle-o"></i> Lista</a></li>
                    <li>
                        <a href="">
                            <i class="fa fa-circle-o"></i>
                            Categorias
                        </a>
                    </li>
                    <li><a href=""><i class="fa fa-circle-o text-success"></i> Votar</a></li>
                </ul>
            </li>
            <li class="treeview"><!-- Check List -->
                <a href="#">
                    <i class="fa fa-edit"></i>
                    <span>Preguntas</span><i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href=""><i class="fa fa-circle-o"></i> Nueva</a></li>
                    <li><a href=""><i class="fa fa-circle-o"></i> Lista</a></li>
                    <li><a href=""><i class="fa fa-circle-o text-success"></i> Responder</a></li>
                </ul>
            </li>
            <li><!-- Diagramas -->
                <a href="">
                    <i class="fa fa-bar-chart-o"></i><span>Diagramas</span>
                </a>
            </li>
            <li class="header">Usuarios</li>
            <li class="treeview"><!-- Check List -->
                <a href="#">
                    <i class="fa fa-user"></i>
                    <span>Usuarios</span><i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href=""><i class="fa fa-circle-o"></i> Nuevo</a></li>
                    <li><a href=""><i class="fa fa-circle-o"></i> Lista</a></li>
                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

superprojectman/templates/projectman/dashboard.html
{% extends 'base/base.html' %}

{% block titulo_ventana %} Bienvenido {% endblock %}
{% block titulo %}Bienvenido{% endblock %}
{% block subtitulo %} {{ request.user }} {% endblock %}

superprojectman/templates/projectman/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>Gestion de Proyectos | ProjectMan</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'admin/css/index_page.css' %}" rel="stylesheet" type="text/css " />

</head>

<body>
<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar" id="myNavbar">
    <a class="w3-bar-item w3-button w3-hover-black w3-hide-medium w3-hide-large w3-right" href="javascript:void(0);" onclick="toggleFunction()" title="Toggle Navigation Menu">
      <i class="fa fa-bars"></i>
    </a>
    <a href="#home" class="w3-bar-item w3-button">HOME</a>
    <a href="#about" class="w3-bar-item w3-button w3-hide-small"><i class="fa fa-user"></i> ABOUT</a>
    <a href="#portfolio" class="w3-bar-item w3-button w3-hide-small"><i class="fa fa-th"></i> PORTFOLIO</a>
    <a href="#contact" class="w3-bar-item w3-button w3-hide-small"><i class="fa fa-envelope"></i> CONTACT</a>
    <a href="{% url 'projectman:login' %}" class="w3-bar-item w3-button w3-hide-small w3-right w3-hover-red">
      LOGIN
    </a>
  </div>

  <!-- Navbar on small screens -->
  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium">
    <a href="#about" class="w3-bar-item w3-button" onclick="toggleFunction()">ABOUT</a>
    <a href="#portfolio" class="w3-bar-item w3-button" onclick="toggleFunction()">PORTFOLIO</a>
    <a href="#contact" class="w3-bar-item w3-button" onclick="toggleFunction()">CONTACT</a>
    <a href="#" class="w3-bar-item w3-button">SEARCH</a>
  </div>
</div>

<!-- First Parallax Image with Logo Text -->
<div class="bgimg-1 w3-display-container w3-opacity-min" id="home">
  <div class="w3-display-middle" style="white-space:nowrap;">
    <span class="w3-center w3-padding-large w3-black w3-xlarge w3-wide w3-animate-opacity"><span class="w3-hide-small">PROJECT</span> MAN</span>
  </div>
</div>

<!-- Container (About Section) -->
<div class="w3-content w3-container w3-padding-64" id="about">
  <h3 class="w3-center">ABOUT US</h3>
  <p class="w3-center"><em>Programming</em></p>
  <p>Somos un grupo de jóvenes amantes de nuestro trabajo y plasmamos esa pasión en cada desarrollo. Actualmente contamos con un equipo de profesionales especializados en diferentes áreas del desarrollo de sitios web, con lo cual aseguramos la calidad de cada trabajo que realizamos: Diseño web, Programación, Sistemas, Comercio Electrónico, Email Marketing y Posicionamiento en Buscadores.

  Ofrecemos servicios completos de Diseño de sitios Web, especializándonos en la creación de aplicaciones web y sitios web auto administrables con poderosos sistemas de gestión verdaderamente fáciles de utilizar..</p>
  <div class="w3-row">
    <div class="w3-col m6 w3-center w3-padding-large">
      <p><b><i class="fa fa-user w3-margin-right"></i>Project Man</b></p><br>
      <img src="/media/about_us.jpg" class="w3-round w3-image w3-opacity w3-hover-opacity-off" alt="Photo of Me" width="500" height="333">
    </div>

    <!-- Hide this text on small devices -->
    <div class="w3-col m6 w3-hide-small w3-padding-large">
      <p>Estamos seguros de la calidad de las soluciones que desarrollamos, por eso ofrecemos a nuestros clientes garantía sobre los proyectos.

      Vemos en cada nuevo proyecto una oportunidad para aprender y para mejorar, y por eso, a través de éstos 10 años hemos implementado en nuestros desarrollos toda la experiencia adquirida.

      De igual forma, tenemos claro que nunca se termina de aprender, por eso estamos en una constante búsqueda de actualización en tecnología y conocimientos y cuando no dominamos un tema, buscamos las respuestas bien sea capacitándonos o por medio de socios estratégicos..</p>
    </div>
  </div>
  <p class="w3-large w3-center w3-padding-16">We are really good at:</p>
  <p class="w3-wide"><i class="fa fa-camera"></i>Photography</p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:90%">90%</div>
  </div>
  <p class="w3-wide"><i class="fa fa-laptop"></i>Web Design</p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:85%">85%</div>
  </div>
  <p class="w3-wide"><i class="fa fa-photo"></i>Photoshop</p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:75%">75%</div>
  </div>
</div>

<div class="w3-row w3-center w3-dark-grey w3-padding-16">
  <div class="w3-quarter w3-section">
    <span class="w3-xlarge">14+</span><br>
    Partners
  </div>
  <div class="w3-quarter w3-section">
    <span class="w3-xlarge">55+</span><br>
    Projects Done
  </div>
  <div class="w3-quarter w3-section">
    <span class="w3-xlarge">89+</span><br>
    Happy Clients
  </div>
  <div class="w3-quarter w3-section">
    <span class="w3-xlarge">150+</span><br>
    Meetings
  </div>
</div>

<!-- Second Parallax Image with Portfolio Text -->
<div class="bgimg-2 w3-display-container w3-opacity-min">
  <div class="w3-display-middle">
    <span class="w3-xxlarge w3-text-white w3-wide">PORTFOLIO</span>
  </div>
</div>

<!-- Container (Portfolio Section) -->
<div class="w3-content w3-container w3-padding-64" id="portfolio">
  <h3 class="w3-center">OUR WORK</h3>
  <p class="w3-center"><em>Here are some of our latest lorem work ipsum tipsum.<br> Click on the images to make them bigger</em></p><br>

  <!-- Responsive Grid. Four columns on tablets, laptops and desktops. Will stack on mobile devices/small screens (100% width) -->
  <div class="w3-row-padding w3-center">
    <div class="w3-col m3">
      <img src="/media/django.png" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="django">
    </div>

    <div class="w3-col m3">
      <img src="/media/python.png" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="Python">
    </div>

    <div class="w3-col m3">
      <img src="/media/postgresql.png" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="Postgresql">
    </div>

    <div class="w3-col m3">
      <img src="/media/pycharm.jpg" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="Pycharm">
    </div>
  </div>

  <div class="w3-row-padding w3-center w3-section">
    <div class="w3-col m3">
      <img src="/media/ubuntu.jpg" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="Ubuntu">
    </div>

    <div class="w3-col m3">
      <img src="" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" >
    </div>

    <div class="w3-col m3">
      <img src="" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" >
    </div>

    <div class="w3-col m3">
      <img src="/media/github.png" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="GitHub">
    </div>
    <button class="w3-button w3-padding-large w3-light-grey" style="margin-top:64px">LOAD MORE</button>
  </div>
</div>

<!-- Modal for full size images on click-->
<div id="modal01" class="w3-modal w3-black" onclick="this.style.display='none'">
  <span class="w3-button w3-large w3-black w3-display-topright" title="Close Modal Image"><i class="fa fa-remove"></i></span>
  <div class="w3-modal-content w3-animate-zoom w3-center w3-transparent w3-padding-64">
    <img id="img01" class="w3-image">
    <p id="caption" class="w3-opacity w3-large"></p>
  </div>
</div>

<!-- Third Parallax Image with Portfolio Text -->
<div class="bgimg-3 w3-display-container w3-opacity-min">
  <div class="w3-display-middle">
     <span class="w3-xxlarge w3-text-white w3-wide">CONTACT</span>
  </div>
</div>

<!-- Container (Contact Section) -->
<div class="w3-content w3-container w3-padding-64" id="contact">
  <h3 class="w3-center">WHERE WE WORK</h3>
  <p class="w3-center"><em>We'd like your feedback!</em></p>

  <div class="w3-row w3-padding-32 w3-section">
    <div class="w3-col m4 w3-container">
      <!-- Add Google Maps -->
      <div id="googleMap" class="w3-round-large w3-greyscale" style="width:100%;height:400px;"></div>
    </div>
    <div class="w3-col m8 w3-panel">
      <div class="w3-large w3-margin-bottom">
        <i class="fa fa-map-marker fa-fw w3-hover-text-black w3-xlarge w3-margin-right"></i> Cartagena, Colombia<br>
        <i class="fa fa-phone fa-fw w3-hover-text-black w3-xlarge w3-margin-right"></i> Phone: +57 305 743 9812<br>
        <i class="fa fa-envelope fa-fw w3-hover-text-black w3-xlarge w3-margin-right"></i> Email: proyecman@managment.com<br>
      </div>
      <p>Leave us a note:</p>
      <form action="/action_page.php" target="_blank">
        <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
          <div class="w3-half">
            <input class="w3-input w3-border" type="text" placeholder="Name" required name="Name">
          </div>
          <div class="w3-half">
            <input class="w3-input w3-border" type="text" placeholder="Email" required name="Email">
          </div>
        </div>
        <input class="w3-input w3-border" type="text" placeholder="Message" required name="Message">
        <button class="w3-button w3-black w3-right w3-section" type="submit">
          <i class="fa fa-paper-plane"></i> SEND MESSAGE
        </button>
      </form>
    </div>
  </div>
</div>

<!-- Footer -->
<footer class="w3-center w3-black w3-padding-64 w3-opacity w3-hover-opacity-off">
  <a href="#home" class="w3-button w3-light-grey"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
  <div class="w3-xlarge w3-section">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
  </div>
 
</footer>
 
<!-- Add Google Maps -->




<script>
function myMap()
{
  myCenter=new google.maps.LatLng(10.3997200, -75.5144400);
  var mapOptions= {
    center:myCenter,
    zoom:12, scrollwheel: false, draggable: false,
    mapTypeId:google.maps.MapTypeId.ROADMAP
  };
  var map=new google.maps.Map(document.getElementById("googleMap"),mapOptions);

  var marker = new google.maps.Marker({
    position: myCenter,
  });
  marker.setMap(map);
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}

// Change style of navbar on scroll
window.onscroll = function() {myFunction()};
function myFunction() {
    var navbar = document.getElementById("myNavbar");
    if (document.body.scrollTop > 100 || document.documentElement.scrollTop > 100) {
        navbar.className = "w3-bar" + " w3-card" + " w3-animate-top" + " w3-white";
    } else {
        navbar.className = navbar.className.replace(" w3-card w3-animate-top w3-white", "");
    }
}

// Used to toggle the menu on small screens when clicking on the menu button
function toggleFunction() {
    var x = document.getElementById("navDemo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?callback=myMap"></script></script>

</body>
</html>